apiVersion: skaffold/v2beta26 
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"
# don't push to docker hub after build
build:
  #local:
  #  push: false
  # link with Google Cloud Build
  googleCloudBuild:
    projectId: ticketing-dev-339410
  artifacts:
    #- image: lcheung/auth
    - image: us.gcr.io/ticketing-dev-339410/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
            
  