apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  # run 1 instance of the image
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lcheung/auth
          #image: us.gcr.io/ticketing-dev-339410/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: auth
    protocol: TCP
    port: 3000
    targetPort: 3000